### ISSUE TITLE
Не собирается если в src есть файл с main методом

### ISSUE THREAD

**Issue by Sammers21** [frnkySila/shersh_gtest_template#3]
кароч такая тема если в src есть main метод то тесты не буду собираться с подобной ошибкой 

```
/home/sammers21/Desktop/algo7/cmake-build-debug/test/dz_test --gtest_filter=* --gtest_color=no
Testing started at 0:03 ...
Usage: /home/sammers21/Desktop/algo7/cmake-build-debug/test/dz_test data-file

Process finished with exit code 1
Empty test suite.
```

**Comment by isgulkov** [comment]
Ой, а почему это? Не потому ли, что драньков там в `test/CMakeLists.txt` сделал

```
add_executable(${PROJECT_TEST_NAME} ${TEST_SRC_FILES}
        ${PROJ_SRC_CPPS}
        ${PROJ_SRC_HEADERS})
```

Надо как-то сделать, чтобы он брал все файлы, кроме мейна. Щас почитаю про функцию `file()`, но чисто с помощью `file(GLOB ...)` это сделать точно нельзя

**Comment by isgulkov** [comment]
Я исключил `main.cpp`, теперь все норм, но если вдруг функция `main()` будет в другом файле, будет та же хуйня
